export default {
  ADD_MESSAGE_START: 'ADD_MESSAGE_START',
  ADD_MESSAGE_OK: 'ADD_MESSAGE_OK',
  ADD_MESSAGE_ERROR: 'ADD_MESSAGE_ERROR',

  ALL_MESSAGE_START: 'ALL_MESSAGE_START',
  ALL_MESSAGE_OK: 'ALL_MESSAGE_OK',
  ALL_MESSAGE_ERROR: 'ALL_MESSAGE_ERROR',
};
